### ISSUE TITLE
Wrong class declaration in grav-plugin-lazy-image/vendor/composer/autoload_real.php

### ISSUE THREAD

**Issue by ganar** [unsaturated/grav-plugin-lazy-image#1]
The current `grav-plugin-lazy-image/vendor/composer/autoload_real.php` has the following class declaration

`class ComposerAutoloaderInit8a23e2ae4d3f41dc1f0d10df35e696c7`

This generates a GravCMS error

Removing the reference `8a23e2ae4d3f41dc1f0d10df35e696c7` in the entire file allows the system to work again

**Comment by unsaturated** [comment]
Thank you for reporting, @ganar. I'll get 1.0.1 released with your recommended fix.

**Comment by unsaturated** [comment]
The `develop` branch is updated, @ganar. Try that and let me know. I failed to reproduce the error with composer update or install.
