### ISSUE TITLE
[Bug] Lazy-image rewrites images set for lazyloading on the template

### ISSUE THREAD

**Issue by ganar** [unsaturated/grav-plugin-lazy-image#3]
Consider checking for `data-src` before execution of lines `118` to `123` [on lazy-image.php](https://github.com/unsaturated/grav-plugin-lazy-image/blob/7a5346b24eb9e60064ab8ad0df11df622910c89a/lazy-image.php#L118)

I did this change and now the plugins works for both images on markdown and on the template.

**Comment by unsaturated** [comment]
Thanks, @ganar. I'll test with that change and likely publish as 1.0.2 if all goes well.
