### ISSUE TITLE
DiDom\Document::load expects parameter 4 to be integer, string given

### ISSUE THREAD

**Issue by ganar** [unsaturated/grav-plugin-lazy-image#5]
I've got this error today:

DiDom\Document::load expects parameter 4 to be integer, string given

I was uploading website to production

23
InvalidArgumentException 
…/user/plugins/lazy-image/vendor/imangazaliev/didom/src/DiDom/Document.php 222
22
DiDom\Document load
…/user/plugins/lazy-image/vendor/imangazaliev/didom/src/DiDom/Document.php 56
21
DiDom\Document __construct
…/user/plugins/lazy-image/lazy-image.php 115
20
Grav\Plugin\LazyImagePlugin updateImages
…/user/plugins/lazy-image/lazy-image.php 89

**Comment by unsaturated** [comment]
Thanks for reporting, @ganar. I'll have to write some checks to ensure `$page->content()` will work with DiDom before passing it along.

**Comment by Blazeflack** [comment]
This still appears to be an issue when visiting a blog page (or the issue has re-appeared).
